// SPDX-License-Identifier: MIT
//
// Node port of Source/C64/gen_menu_regs_i.py (Copyright (c) 2026 Travis Smith, MIT).
//
// Menu_Regs.h is the single hand-edited source of truth for the register/enum map shared
// between the Teensy firmware and the C64 assembly code. The region between the "These need
// to match C64 Code" and "End C64 matching" marker comments is mechanically translated into
// ACME assignment lines. Menu_Regs.i is a build output: edit Menu_Regs.h instead, then
// rebuild (`npm run build:c64` regenerates it first, every time).
import fs from 'node:fs';
import path from 'node:path';

export const MENU_REGS_H = 'Source/Teensy/MinimalBoot/Common/Menu_Regs.h';
export const MENU_REGS_I = 'Source/C64/MainMenuCRT/source/Menu_Regs.i';

const START_MARKER = 'These need to match C64 Code';
const END_MARKER = 'End C64 matching';
const IOH_ENUM_NAME = 'enumIOHandlers';

const HEADER = `; MIT License
;
; Copyright (c) 2026 Travis Smith
;
; Permission is hereby granted, free of charge, to any person obtaining a copy of this software
; and associated documentation files (the "Software"), to deal in the Software without
; restriction, including without limitation the rights to use, copy, modify, merge, publish,
; distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom
; the Software is furnished to do so, subject to the following conditions:
;
; The above copyright notice and this permission notice shall be included in all copies or
; substantial portions of the Software.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
; BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
; NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
; DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

; AUTO-GENERATED by tools/lib/menu-regs.mjs from Teensy/MinimalBoot/Common/Menu_Regs.h -- do not hand-edit.

;!!!!!!!!!!!!!!!!!!!!These need to match Teensy Code: Menu_Regs.h !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`;

const FOOTER = ';!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  End Teensy matching  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!';

const MEMBER_RE = /^(?<name>[A-Za-z_]\w*)\s*(=\s*(?<val>.+))?$/;

function splitComment(text) {
  const idx = text.indexOf('//');
  if (idx === -1) return [text.trimEnd(), null];
  return [text.slice(0, idx).trimEnd(), text.slice(idx)];
}

function stripTrailingComma(code) {
  code = code.trimEnd();
  return code.endsWith(',') ? code.slice(0, -1).trimEnd() : code;
}

// A plain decimal, 0x or 0b literal, or null for anything else (an expression, a macro...).
function parseIntLiteral(val) {
  val = val.trim();
  const sign = val.startsWith('-') ? -1 : 1;
  const digits = val.replace(/^[+-]/, '');
  let m;
  if ((m = /^0x([0-9a-f]+)$/i.exec(digits))) return sign * parseInt(m[1], 16);
  if ((m = /^0b([01]+)$/i.exec(digits))) return sign * parseInt(m[1], 2);
  if (/^\d+$/.test(digits)) return sign * parseInt(digits, 10);
  return null;
}

// Returns [outputLine, valueForTheFollowingBareMember].
function transformMember(code, comment, nextValue) {
  const m = MEMBER_RE.exec(code);
  if (!m) throw new Error(`Could not parse enum/define member: '${code}'`);
  const { name } = m.groups;
  let { val } = m.groups;
  if (val === undefined) {
    if (nextValue === null) {
      throw new Error(
        `${name} has no explicit value and the auto-increment value is unknown ` +
        `(previous member's value wasn't a plain literal). Give ${name} an explicit '= value' in Menu_Regs.h.`,
      );
    }
    val = String(nextValue);
  }
  const literal = parseIntLiteral(val);
  const following = literal !== null ? literal + 1 : null;
  let line = `   ${name} = ${val}`;
  if (comment) line += ` ;${comment.slice(2)}`;
  return [line, following];
}

function transformRegion(lines) {
  const out = [];
  let nextValue = null;
  for (const raw of lines) {
    const stripped = raw.trim();

    if (!stripped) {
      out.push('');
      continue;
    }
    if (stripped === '{') continue;
    if (stripped.startsWith('{')) {
      // Some enum-opening braces carry a trailing comment (e.g. the EEPROM address the
      // enum's values get stored at); keep it as a standalone comment line, drop the brace.
      const [, comment] = splitComment(stripped);
      if (comment) out.push(`;${comment.slice(2)}`);
      continue;
    }
    if (stripped.startsWith('};')) {
      nextValue = null;
      out.push('');
      continue;
    }
    if (stripped.startsWith('enum')) {
      out.push(`;${stripped}`);
      nextValue = 0;
      continue;
    }
    if (stripped.startsWith('#define')) {
      let [code, comment] = splitComment(stripped.slice('#define'.length).trim());
      code = code.replace(/\s+/, ' ').replace(' ', ' = ');
      out.push(transformMember(code, comment, null)[0]);
      continue;
    }
    if (stripped.startsWith('//')) {
      out.push(`;${stripped.slice(2)}`);
      continue;
    }

    let [code, comment] = splitComment(stripped);
    code = stripTrailingComma(code);
    let line;
    [line, nextValue] = transformMember(code, comment, nextValue);
    out.push(line);
  }
  return out;
}

// IOH_None is the first (always-0) member of enumIOHandlers, defined *outside* the synced
// region. C64 code needs this one constant, so pull it in explicitly rather than widening
// what counts as the synced C64/Teensy region.
function findIohNone(hLines) {
  const enumRe = new RegExp(`\\benum\\s+${IOH_ENUM_NAME}\\b`);
  const i = hLines.findIndex((l) => enumRe.test(l));
  if (i === -1) throw new Error(`Could not find enum ${IOH_ENUM_NAME} in Menu_Regs.h`);
  for (const memberLine of hLines.slice(i + 1)) {
    const s = memberLine.trim();
    if (!s || s === '{' || s.startsWith('//')) continue;
    let [code] = splitComment(s);
    code = stripTrailingComma(code);
    const m = MEMBER_RE.exec(code);
    if (!m) throw new Error(`Could not parse first ${IOH_ENUM_NAME} member: '${s}'`);
    const { name, val } = m.groups;
    if (val !== undefined && parseIntLiteral(val) !== 0) {
      throw new Error(
        `First member of enum ${IOH_ENUM_NAME} is ${name} = ${val}, expected 0 (IOH_None must stay ` +
        'first/always-0 -- see comment in Menu_Regs.h). Update tools/lib/menu-regs.mjs\'s IOH_None handling.',
      );
    }
    return name;
  }
  throw new Error(`Could not find enum ${IOH_ENUM_NAME} in Menu_Regs.h`);
}

// Menu_Regs.h's text -> Menu_Regs.i's text.
export function generateMenuRegsI(hText) {
  const hLines = hText.split(/\r\n|\r|\n/);
  const start = hLines.findIndex((l) => l.includes(START_MARKER));
  const end = hLines.findIndex((l) => l.includes(END_MARKER));
  if (start === -1 || end === -1 || end <= start) {
    throw new Error('could not locate synced region markers in Menu_Regs.h');
  }

  const body = transformRegion(hLines.slice(start + 1, end));
  const iohNone = findIohNone(hLines);
  return [
    HEADER,
    ...body,
    '',
    `   ${iohNone} = 0  ;only part of ${IOH_ENUM_NAME} used, see Menu_Regs.h`,
    FOOTER,
  ].join('\n') + '\n';
}

// Regenerates Menu_Regs.i under `root`; returns its path.
export function writeMenuRegsI(root) {
  const dst = path.join(root, MENU_REGS_I);
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.writeFileSync(dst, generateMenuRegsI(fs.readFileSync(path.join(root, MENU_REGS_H), 'utf8')));
  return dst;
}
