// MIT License
// 
// Copyright (c) 2023 Travis Smith
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software 
// and associated documentation files (the "Software"), to deal in the Software without 
// restriction, including without limitation the rights to use, copy, modify, merge, publish, 
// distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom 
// the Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all copies or 
// substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
// BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


// Build profile for the extension image.
//
// This image exists because of its memory map, not its features. It reserves
// 96 KiB of ITCM and 192 KiB of DTCM for the module and caps its own heap, none
// of which the ordinary minimal image can do while still holding a megabyte of
// cartridge. The linker script generated by tools/lib/extension-image.mjs
// asserts every one of those boundaries at link time.
//
// It must be built by tools/build-firmware.mjs --with-extensions; the stock
// IDE linker profile cannot safely execute a module.
#if !defined(VM_HOST_PROFILE) || !defined(USB_DISABLED)
#error "Build this image with tools/build-firmware.mjs --with-extensions"
#endif

#define MinimumBuild         //Must be defined for minimal build to identify in common files
#define FeatVMHost           //Compile the extension host and its IO_Handler hooks

// No Ethernet and no bank swapping: this image loads one 16 KiB client
// cartridge into RAM and then hands the machine to the module.
#define Num8kSwapBuffers  2
#define EthernetDeduction 0
#define MaxRAM_ImageSize  16
