#!/usr/bin/env python3
# MIT License
#
# Copyright (c) 2026 Travis Smith
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software
# and associated documentation files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or
# substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
# BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""Regenerate Menu_Regs.i (ACME) from Menu_Regs.h (C).

Menu_Regs.h is the single hand-edited source of truth for the register/enum map
shared between the Teensy firmware and the C64 assembly code. The region between
the "These need to match C64 Code" and "End C64 matching" marker comments is
mechanically translated here into ACME assignment lines. Menu_Regs.i is a build
output -- edit Menu_Regs.h instead, then re-run this script (wired into
SetToolPaths.bat, so every C64 build regenerates it).
"""
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SRC_H = SCRIPT_DIR / ".." / "Teensy" / "MinimalBoot" / "Common" / "Menu_Regs.h"
DST_I = SCRIPT_DIR / "MainMenuCRT" / "source" / "Menu_Regs.i"

START_MARKER = "These need to match C64 Code"
END_MARKER = "End C64 matching"
IOH_ENUM_NAME = "enumIOHandlers"

HEADER = '''; MIT License
;
; Copyright (c) 2026 Travis Smith
;
; Permission is hereby granted, free of charge, to any person obtaining a copy of this software
; and associated documentation files (the "Software"), to deal in the Software without
; restriction, including without limitation the rights to use, copy, modify, merge, publish,
; distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom
; the Software is furnished to do so, subject to the following conditions:
;
; The above copyright notice and this permission notice shall be included in all copies or
; substantial portions of the Software.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
; BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
; NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
; DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

; AUTO-GENERATED by gen_menu_regs_i.py from Teensy/MinimalBoot/Common/Menu_Regs.h -- do not hand-edit.

;!!!!!!!!!!!!!!!!!!!!These need to match Teensy Code: Menu_Regs.h !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
'''

FOOTER = """
;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  End Teensy matching  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
"""

MEMBER_RE = re.compile(r"^(?P<name>[A-Za-z_]\w*)\s*(=\s*(?P<val>.+))?$")


def split_comment(text):
    idx = text.find("//")
    if idx == -1:
        return text.rstrip(), None
    return text[:idx].rstrip(), text[idx:]


def strip_trailing_comma(code):
    code = code.rstrip()
    if code.endswith(","):
        code = code[:-1].rstrip()
    return code


def parse_int_literal(val):
    val = val.strip()
    try:
        if val.lower().startswith("0x"):
            return int(val, 16)
        if val.lower().startswith("0b"):
            return int(val, 2)
        return int(val, 10)
    except ValueError:
        return None


def transform_member(code, comment, next_value):
    """Returns (output_line, next_value_for_following_bare_member)."""
    m = MEMBER_RE.match(code)
    if not m:
        raise ValueError(f"Could not parse enum/define member: {code!r}")
    name = m.group("name")
    val = m.group("val")
    if val is None:
        if next_value is None:
            raise ValueError(
                f"{name} has no explicit value and the auto-increment value is "
                f"unknown (previous member's value wasn't a plain literal). "
                f"Give {name} an explicit '= value' in Menu_Regs.h."
            )
        val = str(next_value)
    literal = parse_int_literal(val)
    following_next = (literal + 1) if literal is not None else None
    line = f"   {name} = {val}"
    if comment:
        line += " ;" + comment[2:]
    return line, following_next


def transform_region(lines):
    out = []
    next_value = None
    in_define_run = False
    for raw in lines:
        stripped = raw.strip()

        if not stripped:
            out.append("")
            continue

        if stripped == "{":
            continue
        if stripped.startswith("{"):
            # Some enum-opening braces carry a trailing comment (e.g. the EEPROM
            # address the enum's values get stored at) -- keep it as a standalone
            # comment line, just drop the brace itself.
            _, comment = split_comment(stripped)
            if comment:
                out.append(";" + comment[2:])
            continue
        if stripped.startswith("};"):
            next_value = None
            out.append("")
            continue

        if stripped.startswith("enum"):
            out.append(";" + stripped)
            next_value = 0
            continue

        if stripped.startswith("#define"):
            code, comment = split_comment(stripped[len("#define"):].strip())
            code = re.sub(r"\s+", " ", code, count=1).replace(" ", " = ", 1)
            line, _ = transform_member(code, comment, None)
            out.append(line)
            continue

        if stripped.startswith("//"):
            out.append(";" + stripped[2:])
            continue

        code, comment = split_comment(stripped)
        code = strip_trailing_comma(code)
        line, next_value = transform_member(code, comment, next_value)
        out.append(line)

    return out


def find_ioh_none(h_lines):
    """IOH_None is the first (always-0) member of enumIOHandlers, defined *outside*
    the synced region -- C64 code needs this one constant, so pull it in explicitly
    rather than widening what counts as the synced C64/Teensy region."""
    for i, line in enumerate(h_lines):
        if re.search(rf"\benum\s+{IOH_ENUM_NAME}\b", line):
            for member_line in h_lines[i + 1:]:
                s = member_line.strip()
                if not s or s == "{" or s.startswith("//"):
                    continue
                code, comment = split_comment(s)
                code = strip_trailing_comma(code)
                m = MEMBER_RE.match(code)
                if not m:
                    raise ValueError(f"Could not parse first {IOH_ENUM_NAME} member: {s!r}")
                name = m.group("name")
                val = m.group("val")
                if val is not None and parse_int_literal(val) != 0:
                    raise ValueError(
                        f"First member of enum {IOH_ENUM_NAME} is {name} = {val}, "
                        f"expected 0 (IOH_None must stay first/always-0 -- see comment "
                        f"in Menu_Regs.h). Update gen_menu_regs_i.py's IOH_None handling."
                    )
                return name
    raise ValueError(f"Could not find enum {IOH_ENUM_NAME} in Menu_Regs.h")


def main():
    h_text = SRC_H.read_text()
    h_lines = h_text.splitlines()

    start_idx = next((i for i, l in enumerate(h_lines) if START_MARKER in l), None)
    end_idx = next((i for i, l in enumerate(h_lines) if END_MARKER in l), None)
    if start_idx is None or end_idx is None or end_idx <= start_idx:
        print("ERROR: could not locate synced region markers in Menu_Regs.h", file=sys.stderr)
        return 1

    body = transform_region(h_lines[start_idx + 1:end_idx])
    ioh_none_name = find_ioh_none(h_lines)

    out_lines = [HEADER.rstrip("\n")]
    out_lines.extend(body)
    out_lines.append("")
    out_lines.append(f"   {ioh_none_name} = 0  ;only part of {IOH_ENUM_NAME} used, see Menu_Regs.h")
    out_lines.append(FOOTER.strip("\n"))

    DST_I.parent.mkdir(parents=True, exist_ok=True)
    DST_I.write_text("\n".join(out_lines) + "\n")
    print(f"Wrote {DST_I}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
